/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:85020f33-e0da-4c00-83ab-05698f3e3ac0",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_8TYLGyvzP",
    "aws_user_pools_web_client_id": "2edibl0eob9l3vnc7q560imd8h",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://7s6tx7pnsvdwlpnsi4v4zw5mmu.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-47gorgfagnhtxdakfa5dskg7gi"
};


export default awsmobile;
